language: "perl"

perl:
  - "5.10"

sudo: required
services:
  - docker

install:
    - docker pull pbspro/pbspro
    - git clone --depth 1 --branch master https://github.com/Ensembl/ensembl-hive
    - env

script:
    - docker run -v /home/travis:/home/travis pbspro/pbspro /home/travis/build/Ensembl/ensembl-hive-pbspro/travisci/setup_docker_and_run_tests.sh

