language: "perl"

perl:
  - "5.10"

sudo: required
services:
  - docker

install:
    - docker pull ensemblorg/ensembl-hive-pbspro
    - env

script:
    - docker run -v /home/travis:/home/travis ensemblorg/ensembl-hive-pbspro /home/travis/build/Ensembl/ensembl-hive-pbspro/travisci/setup_docker_and_run_tests.sh

